const LANGUAGES = [
    { id: 'python', name: 'Python', icon: 'fa-brands fa-python', color: '#3776AB', lessons: 7 },
    { id: 'javascript', name: 'JavaScript', icon: 'fa-brands fa-square-js', color: '#F7DF1E', lessons: 7 },
    { id: 'html', name: 'HTML', icon: 'fa-brands fa-html5', color: '#E34F26', lessons: 5 },
    { id: 'css', name: 'CSS', icon: 'fa-brands fa-css3-alt', color: '#1572B6', lessons: 5 },
    { id: 'sql', name: 'SQL', icon: 'fa-solid fa-database', color: '#4479A1', lessons: 5 },
    { id: 'java', name: 'Java', icon: 'fa-solid fa-mug-saucer', color: '#ED8B00', lessons: 5 },
    { id: 'cpp', name: 'C++', icon: 'fa-solid fa-bolt', color: '#00599C', lessons: 5 },
    { id: 'csharp', name: 'C#', icon: 'fa-solid fa-crosshairs', color: '#239120', lessons: 5 },
    { id: 'php', name: 'PHP', icon: 'fa-brands fa-php', color: '#777BB4', lessons: 4 },
    { id: 'ruby', name: 'Ruby', icon: 'fa-solid fa-gem', color: '#CC342D', lessons: 4 },
    { id: 'go', name: 'Go', icon: 'fa-solid fa-circle', color: '#00ADD8', lessons: 4 },
    { id: 'rust', name: 'Rust', icon: 'fa-solid fa-shield-halved', color: '#DEA584', lessons: 4 },
    { id: 'typescript', name: 'TypeScript', icon: 'fa-solid fa-file-code', color: '#3178C6', lessons: 4 },
    { id: 'swift', name: 'Swift', icon: 'fa-solid fa-code', color: '#F05138', lessons: 4 },
    { id: 'kotlin', name: 'Kotlin', icon: 'fa-solid fa-wind', color: '#7F52FF', lessons: 4 }
];

const COURSES = {};

COURSES.python = {
    title: 'Python', icon: 'fa-brands fa-python',
    lessons: [
        { id: 1, title: 'Decouvre Python !', content: 'Python est un langage de programmation. C\'est comme donner des instructions a un ordinateur ! Imagine que tu parles a un robot et que tu lui dis quoi faire. Python est facile a lire car il ressemble presque a du francais ou de l\'anglais. Avec Python, tu peux creer des jeux, des sites web, et meme des programmes qui dessinent ! Pour commencer, on utilise la fonction print() qui affiche du texte a l\'ecran. Le texte doit etre entre guillemets.', code: '# Un commentaire commence par #\n# Le programme ignore les commentaires\n\nprint("Bonjour le monde!")\nprint("Je code en Python!")\n\n# Tu peux aussi faire des calculs\nprint(2 + 3)  # Affiche 5\nprint(10 - 4) # Affiche 6', quiz: { questions: [{ q: 'Quelle fonction utilises-tu pour afficher du texte en Python ?', options: ['affiche()', 'print()', 'ecris()', 'montre()'], answer: 1 }, { q: 'Que fait Python avec le symbole # ?', options: ['Il efface la ligne', 'C\'est un commentaire, il ignore', 'Il imprime la ligne', 'Il ajoute un chiffre'], answer: 1 }] } },
        { id: 2, title: 'Les Variables : Range Tes Infos !', content: 'Une variable, c\'est comme une boite dans laquelle tu ranges une information. Tu peux y mettre un nombre, du texte, ou du vrai/faux. Tu donnes un nom a ta boite, et ensuite tu peux reutiliser ce que tu as range quand tu veux ! En Python, pas besoin de dire quel type de chose tu ranges : Python le devine tout seul.', code: '# Creer des variables\nprenom = "Othniel"\nage = 22\nest_etudiant = True\n\n# Afficher les variables\nprint(prenom)\nprint(age)\n\n# Calculer avec des variables\nannee_prochaine = age + 1\nprint(annee_prochaine)\n\n# On peut changer la valeur\nprenom = "Ange-Aurel"\nprint(prenom)', quiz: { questions: [{ q: 'A quoi sert une variable en Python ?', options: ['A ranger une information', 'A effacer un texte', 'A dessiner une image', 'A faire un site web'], answer: 0 }, { q: 'Si age = 10, que donne age + 5 ?', options: ['5', '10', '15', '105'], answer: 2 }] } },
        { id: 3, title: 'Les Conditions : Prendre des Decisions', content: 'Parfois, tu veux que ton programme fasse des choses differentes selon la situation. C\'est comme un jeu de societe : "Si tu fais 6, tu rejoues, sinon tu passes ton tour". En Python, on utilise "if" pour dire "si", "elif" pour "sinon si", et "else" pour "sinon". Les符号 de comparaison sont : == (egal), != (different), < (plus petit), > (plus grand), <=, >=.', code: 'age = 18\n\nif age >= 18:\n    print("Tu es majeur !")\nelse:\n    print("Tu es mineur.")\n\nnote = 15\nif note >= 18:\n    print("Excellent !")\nelif note >= 14:\n    print("Tres bien !")\nelif note >= 10:\n    print("Passable.")\nelse:\n    print("A revoir...")', quiz: { questions: [{ q: 'Quel mot Python signifie "si" ?', options: ['si', 'if', 'when', 'maybe'], answer: 1 }, { q: 'Que veut dire >= en Python ?', options: ['Plus grand que', 'Plus grand ou egal', 'Egal', 'Different'], answer: 1 }] } },
        { id: 4, title: 'Les Boucles : Repeter Sans Arret', content: 'Les boucles permettent de repeter une action plusieurs fois sans avoir a ecrire le meme code encore et encore. C\'est comme dire "compte de 1 a 10" au lieu d\'ecrire un, deux, trois... Il y a deux boucles : "for" (pour chaque element) et "while" (tant qu\'une condition est vraie). range(5) cree les nombres 0, 1, 2, 3, 4.', code: '# Boucle for : repete 5 fois\nfor i in range(5):\n    print("Tour numero", i)\n\n# Boucle while : tant que c\'est vrai\ncompteur = 0\nwhile compteur < 3:\n    print("Compteur:", compteur)\n    compteur = compteur + 1', quiz: { questions: [{ q: 'Que fait la boucle for ?', options: ['Elle repete du code', 'Elle efface du code', 'Elle verifie une condition', 'Elle cree une variable'], answer: 0 }, { q: 'Combien de fois "range(3)" fait-il repeter ?', options: ['2 fois', '3 fois', '4 fois', '1 fois'], answer: 1 }] } },
        { id: 5, title: 'Les Listes : Ranger Plusieurs Choses', content: 'Une liste, c\'est comme une boite qui peut contenir plusieurs choses a la fois. Tu peux y mettre des noms, des nombres, ou meme un melange des deux. Chaque element a une position (on commence a 0). On peut ajouter avec append(), enlever avec remove(), ou modifier directement. len() donne le nombre d\'elements.', code: '# Creer une liste\namis = ["Alice", "Bob", "Charlie"]\nprint(amis[0])  # Alice (position 0)\n\n# Ajouter\namis.append("David")\nprint(amis)\n\n# Modifier\namis[1] = "Bernard"\n\n# Compter\nprint(len(amis))  # 4\n\n# Boucle sur une liste\nfor ami in amis:\n    print("Salut", ami)', quiz: { questions: [{ q: 'Quelle est la premiere position dans une liste ?', options: ['1', '0', '-1', 'Premier'], answer: 1 }, { q: 'Comment ajoutes-tu un element a une liste ?', options: ['ajoute()', 'append()', 'add()', 'plus()'], answer: 1 }] } },
        { id: 6, title: 'Les Fonctions : Cree Tes Propres Actions', content: 'Une fonction, c\'est comme une recette de cuisine. Tu ecris la recette une fois, et tu peux l\'utiliser plusieurs fois quand tu veux. En Python, on cree une fonction avec "def" (definir). Tu donnes un nom a ta fonction, tu ecris ce qu\'elle fait, et ensuite tu peux l\'appeler quand tu veux. Le mot "return" renvoie un resultat.', code: 'def dire_bonjour(prenom):\n    print("Bonjour", prenom, "!")\n\ndire_bonjour("Alice")\ndire_bonjour("Bob")\n\n# Fonction qui retourne une valeur\ndef double(nombre):\n    return nombre * 2\n\nresultat = double(5)\nprint(resultat)  # 10', quiz: { questions: [{ q: 'Quel mot utilise-t-on pour creer une fonction ?', options: ['function', 'def', 'creer', 'faire'], answer: 1 }, { q: 'Que fait "return" dans une fonction ?', options: ['Elle repete la fonction', 'Elle renvoie une valeur', 'Elle arrete le programme', 'Elle imprime un texte'], answer: 1 }] } },
        { id: 7, title: 'Les Dictionnaires : Ranger avec des Etiquettes', content: 'Un dictionnaire, c\'est comme une liste mais chaque element a une etiquette (une cle) au lieu d\'une position. Au lieu de dire "donne-moi l\'element numero 0", tu dis "donne-moi l\'element qui s\'appelle \'nom\'". C\'est tres pratique pour ranger des informations sur une personne ou un objet. On utilise les accolades {} et le symbole : pour associer une cle a sa valeur.', code: 'personne = {\n    "prenom": "Othniel",\n    "age": 22,\n    "ville": "Paris"\n}\n\nprint(personne["prenom"])\nprint(personne["ville"])\n\npersonne["age"] = 23\npersonne["metier"] = "Developpeur"\n\nprint(personne)\n\n# Parcourir un dictionnaire\nfor cle, valeur in personne.items():\n    print(cle, ":", valeur)', quiz: { questions: [{ q: 'Quelle est la difference entre une liste et un dictionnaire ?', options: ['La liste utilise des positions, le dictionnaire utilise des cles', 'Il n\'y a pas de difference', 'Le dictionnaire est plus lent', 'La liste peut tout stocker'], answer: 0 }, { q: 'Comment accedes-tu a la valeur d\'une cle "nom" ?', options: ['personne.nom', 'personne["nom"]', 'personne(nom)', 'personne->nom'], answer: 1 }] } }
    ],
    exam: { passingScore: 7,
        questions: [
            { q: 'Quelle fonction affiche du texte en Python ?', options: ['affiche()', 'print()', 'ecris()', 'montre()'], answer: 1 },
            { q: 'Que fait le symbole # en Python ?', options: ['Ajoute un commentaire', 'Imprime du texte', 'Cree une variable', 'Efface la ligne'], answer: 0 },
            { q: 'Si x = 5, que donne x + 3 ?', options: ['53', '8', '5', '3'], answer: 1 },
            { q: 'Quel mot-cle signifie "si" en Python ?', options: ['si', 'if', 'when', 'then'], answer: 1 },
            { q: 'Quelle boucle repete pour chaque element ?', options: ['while', 'for', 'repeat', 'loop'], answer: 1 },
            { q: 'Quelle est la premiere position dans une liste ?', options: ['1', '0', '-1', 'Premier'], answer: 1 },
            { q: 'Comment ajoute-t-on a la fin d\'une liste ?', options: ['append()', 'add()', 'push()', 'insert()'], answer: 0 },
            { q: 'Quel mot pour creer une fonction ?', options: ['function', 'def', 'creer', 'faire'], answer: 1 },
            { q: 'Que fait return ?', options: ['Repete', 'Renvoie une valeur', 'Imprime', 'Cree'], answer: 1 },
            { q: 'Comment accede-t-on a une cle de dictionnaire ?', options: ['dict.cle', 'dict["cle"]', 'dict(cle)', 'dict->cle'], answer: 1 }
        ]
    }
};

COURSES.javascript = {
    title: 'JavaScript', icon: 'fa-brands fa-square-js',
    lessons: [
        { id: 1, title: 'Bienvenue en JavaScript !', content: 'JavaScript est le langage qui rend les sites web vivants ! Quand tu cliques sur un bouton et que quelque chose se passe, c\'est surement du JavaScript. Il fonctionne dans ton navigateur (Chrome, Firefox, Edge) et permet de creer des jeux, des animations, et des applications web. Pour afficher un message, on utilise console.log().', code: '// Ceci est un commentaire\n\nconsole.log("Bonjour le monde !");\nconsole.log("Je code en JavaScript !");\n\n// Tu peux aussi faire des calculs\nconsole.log(2 + 3);  // 5\nconsole.log(10 - 4); // 6', quiz: { questions: [{ q: 'Ou s\'execute JavaScript principalement ?', options: ['Sur un serveur', 'Dans le navigateur', 'Dans un fichier Word', 'Dans une calculatrice'], answer: 1 }, { q: 'Quelle fonction affiche un message dans la console ?', options: ['print()', 'console.log()', 'affiche()', 'ecris()'], answer: 1 }] } },
        { id: 2, title: 'Les Variables en JavaScript', content: 'Comme en Python, les variables sont des boites pour ranger des informations. En JavaScript, on utilise "let" pour une variable qui peut changer, et "const" pour une valeur qui ne changera jamais. C\'est pratique pour etre sur que personne ne modifie une valeur importante ! Les textes s\'appellent des "strings" et les nombres des "numbers".', code: 'let prenom = "Othniel";\nprenom = "Ange-Aurel";  // OK\nconsole.log(prenom);\n\nconst age = 22;\n// age = 23;  // Erreur !\n\nlet nom = "Alice";      // string\nlet nombre = 10;        // number\nlet estVrai = true;     // boolean\n\nconsole.log("Je m\'appelle " + nom + " et j\'ai " + age + " ans");', quiz: { questions: [{ q: 'Difference entre let et const ?', options: ['let change, const non', 'const change, let non', 'Aucune difference', 'let pour nombres'], answer: 0 }, { q: 'Comment ecris-tu un texte en JavaScript ?', options: ['Entre guillemets ""', 'Entre asterisques **', 'Entre parentheses ()', 'Entre crochets []'], answer: 0 }] } },
        { id: 3, title: 'Les Conditions en JavaScript', content: 'Comme en Python, on utilise if/else pour prendre des decisions. La syntaxe est un peu differente : on met la condition entre parentheses () et les actions entre accolades {}. Les symboles de comparaison sont : === pour "est strictement egal a" (valeur ET type), !== pour "est different de", > pour "plus grand que", < pour "plus petit que".', code: 'let age = 18;\n\nif (age >= 18) {\n    console.log("Tu es majeur !");\n} else {\n    console.log("Tu es mineur.");\n}\n\nlet note = 15;\nif (note >= 18) {\n    console.log("Excellent !");\n} else if (note >= 14) {\n    console.log("Tres bien !");\n} else {\n    console.log("A revoir...");\n}\n\nconsole.log(5 === "5");  // false', quiz: { questions: [{ q: 'Quels symboles entourent la condition en JS ?', options: ['Crochets []', 'Parentheses ()', 'Accolades {}', 'Guillemets ""'], answer: 1 }, { q: 'Que signifie === ?', options: ['Egal a peu pres', 'Strictement egal', 'A peu pres', 'Different'], answer: 1 }] } },
        { id: 4, title: 'Les Fonctions en JavaScript', content: 'Les fonctions en JavaScript sont des actions que tu peux reutiliser. Tu peux les creer de deux facons : avec le mot "function" (classique) ou avec une "fonction fleche" => (moderne). Les fonctions peuvent prendre des parametres (des infos en entree) et retourner un resultat avec return.', code: 'function direBonjour(prenom) {\n    console.log("Bonjour " + prenom + " !");\n}\ndireBonjour("Alice");\n\n// Fonction fleche\nconst double = (nombre) => {\n    return nombre * 2;\n};\nconsole.log(double(5));  // 10\n\n// Version courte\nconst carre = (n) => n * n;\nconsole.log(carre(4));  // 16', quiz: { questions: [{ q: 'Symbole pour fonction fleche ?', options: ['->', '=>', '=]', '||'], answer: 1 }, { q: 'Que fait "return" ?', options: ['Repete', 'Renvoie une valeur', 'Arrete le programme', 'Imprime'], answer: 1 }] } },
        { id: 5, title: 'Les Tableaux en JavaScript', content: 'Les tableaux (arrays) sont comme les listes en Python : ils rangent plusieurs elements. On utilise les crochets [] et chaque element a une position qui commence a 0. On peut ajouter avec push(), enlever avec pop(), et la propriete length donne le nombre d\'elements.', code: 'let fruits = ["pomme", "banane", "orange"];\nconsole.log(fruits[0]);  // pomme\n\nfruits.push("kiwi");\nconsole.log(fruits);\n\nfruits.pop();\nconsole.log(fruits.length);  // 3\n\nfor (let fruit of fruits) {\n    console.log("Jaime les " + fruit);\n}', quiz: { questions: [{ q: 'Methode pour ajouter a un tableau ?', options: ['add()', 'push()', 'append()', 'plus()'], answer: 1 }, { q: 'Propriete pour la taille d\'un tableau ?', options: ['taille', 'length', 'nombre', 'size'], answer: 1 }] } },
        { id: 6, title: 'Les Objets en JavaScript', content: 'Les objets sont comme les dictionnaires en Python : ils associent des cles a des valeurs. En JavaScript, on utilise les accolades {} et on ecrit "cle: valeur". C\'est parfait pour representer une chose avec plusieurs proprietes, comme une personne.', code: 'let personne = {\n    prenom: "Othniel",\n    age: 22,\n    ville: "Paris",\n    saluer: function() {\n        return "Bonjour, je suis " + this.prenom;\n    }\n};\n\nconsole.log(personne.prenom);\nconsole.log(personne["age"]);\nconsole.log(personne.saluer());\n\npersonne.age = 23;\npersonne.metier = "Developpeur";', quiz: { questions: [{ q: 'Comment acceder a la propriete "nom" ?', options: ['objet.nom', 'objet->nom', 'objet(nom)', 'objet[nom]'], answer: 0 }, { q: 'Symboles pour un objet ?', options: ['Crochets []', 'Parentheses ()', 'Accolades {}', 'Guillemets ""'], answer: 2 }] } },
        { id: 7, title: 'Le DOM : Interagir avec ta Page', content: 'Le DOM (Document Object Model) est l\'interface qui permet a JavaScript de parler avec ta page HTML. Grace a lui, tu peux modifier le texte, les couleurs, ou reagir aux clics. Quand tu cliques sur un bouton et qu\'une action se produit, c\'est le DOM qui est utilise.', code: 'let titre = document.querySelector("h1");\ntitre.textContent = "Nouveau titre !";\ntitre.style.color = "blue";\n\nlet bouton = document.querySelector("button");\nbouton.addEventListener("click", function() {\n    alert("Tu as clique !");\n});\n\nlet p = document.createElement("p");\np.textContent = "Je suis nouveau !";\ndocument.body.appendChild(p);', quiz: { questions: [{ q: 'Que signifie DOM ?', options: ['Document Object Model', 'Digital Object Management', 'Document Online Model', 'Dynamic Object Method'], answer: 0 }, { q: 'Methode pour selectionner un element CSS ?', options: ['getElement()', 'querySelector()', 'findElement()', 'selectCSS()'], answer: 1 }] } }
    ],
    exam: { passingScore: 7,
        questions: [
            { q: 'Ou s\'execute JS ?', options: ['Serveur', 'Navigateur', 'Word', 'Calculatrice'], answer: 1 },
            { q: 'Difference let et const ?', options: ['let change, const non', 'const change, let non', 'Aucune', 'let pour nombres'], answer: 0 },
            { q: 'Que signifie === ?', options: ['Approximatif', 'Strictement egal', 'Different', 'A peu pres'], answer: 1 },
            { q: 'Symbole fonction fleche ?', options: ['->', '=>', '=]', '||'], answer: 1 },
            { q: 'Methode pour ajouter a un tableau ?', options: ['add()', 'push()', 'append()', 'plus()'], answer: 1 },
            { q: 'Propriete taille tableau ?', options: ['taille', 'length', 'nombre', 'size'], answer: 1 },
            { q: 'Acceder a objet.nom ?', options: ['objet.nom', 'objet->nom', 'objet(nom)', 'objet[nom]'], answer: 0 },
            { q: 'Que signifie DOM ?', options: ['Document Object Model', 'Digital Object Management', 'Document Online Model', 'Dynamic Object Method'], answer: 0 },
            { q: 'Methode pour selectionner ?', options: ['getElement()', 'querySelector()', 'findElement()', 'selectCSS()'], answer: 1 },
            { q: 'Symbole commentaire JS ?', options: ['#', '//', '/*', '--'], answer: 1 }
        ]
    }
};

COURSES.html = {
    title: 'HTML', icon: 'fa-brands fa-html5',
    lessons: [
        { id: 1, title: 'La Structure de Base : Le Squelette d\'une Page', content: 'HTML signifie HyperText Markup Language. C\'est le langage qui sert a construire les pages web. Chaque page HTML est composee de "balises" (tags). Les balises sont comme des briques qui construisent la page. Elles s\'ecrivent entre < >. La plupart des balises ont une ouvrante <balise> et une fermante </balise>.\n\nVoici les balises de base d\'une page HTML :\n- <!DOCTYPE html> : cette balise speciale dit au navigateur "Attention, ceci est une page HTML !". Elle est obligatoire et s\'ecrit tout en haut.\n- <html> : c\'est la balise principale qui contient TOUTE la page. Tout le code HTML doit etre a l\'interieur de <html>...</html>.\n- <head> : c\'est l\'en-tete de la page. Elle contient des informations pour le navigateur, comme le titre de l\'onglet (<title>) et les reglages (<meta>). Ce qui est dans <head> n\'est PAS visible sur la page.\n- <body> : c\'est le corps de la page. TOUT ce qui est visible a l\'ecran (textes, images, boutons) se trouve dans <body>.</body> .\n- <title> : cette balise definit le texte qui s\'affiche dans l\'onglet du navigateur. Elle se met dans <head>.\n- <meta charset="UTF-8"> : cette balise dit au navigateur d\'utiliser l\'encodage UTF-8 pour afficher correctement les accents et caracteres speciaux (e, à, ü...).', code: '<!DOCTYPE html>\n<html>\n<head>\n    <!-- Le titre apparait dans l\'onglet du navigateur -->\n    <title>Ma Premiere Page</title>\n    <!-- UTF-8 permet d\'afficher les accents -->\n    <meta charset="UTF-8">\n</head>\n<body>\n    <!-- Ceci est visible sur la page -->\n    <h1>Bienvenue sur CodeLux !</h1>\n    <p>Ceci est mon premier paragraphe.</p>\n    <p>HTML est genial !</p>\n</body>\n</html>', quiz: { questions: [{ q: 'Que contient la balise <head> ?', options: ['Le contenu visible de la page', 'Les infos pour le navigateur (titre, encodage)', 'Les images et les videos', 'Les liens vers d\'autres pages'], answer: 1 }, { q: 'A quoi sert la balise <title> ?', options: ['A afficher un titre sur la page', 'A donner un nom a l\'onglet du navigateur', 'A creer un grand titre', 'A ecrire un commentaire'], answer: 1 }] } },
        { id: 2, title: 'Les Titres et les Paragraphes : Organiser le Texte', content: 'Quand tu ecris un document, tu as besoin de titres et de paragraphes. En HTML, on utilise des balises speciales pour cela.\n\nLes titres (headings) :\n- <h1> : le titre LE PLUS important de la page. Il ne devrait y en avoir qu\'un seul par page. C\'est le plus grand.\n- <h2> : un titre de section (plus petit que h1).\n- <h3>, <h4>, <h5>, <h6> : des titres de plus en plus petits. <h6> est le plus petit.\n\nLes textes :\n- <p> : un paragraphe. Chaque <p> cree un nouveau bloc de texte avec un espace avant et apres.\n- <strong> : met le texte en gras pour montrer qu\'il est important (les lecteurs d\'ecran le soulignent).\n- <b> : met juste le texte en gras (sans importance particuliere).\n- <em> : met le texte en italique pour insister sur un mot.\n- <i> : met juste le texte en italique.\n- <br> : fait un saut de ligne (retour a la ligne). Il n\'a pas de balise fermante !\n- <!-- commentaire --> : ceci est un commentaire. Le navigateur ne l\'affiche pas. Ca sert a laisser des notes pour les developpeurs.', code: '<h1>Titre principal de la page (h1)</h1>\n<h2>Section importante (h2)</h2>\n<h3>Sous-section (h3)</h3>\n\n<p>Ceci est un paragraphe normal. Le navigateur\najoute automatiquement un espace avant et apres.</p>\n\n<p>Ceci est un <strong>texte important</strong> (en gras)\net un <em>texte insiste</em> (en italique).</p>\n\n<p>Premiere ligne<br>\nDeuxieme ligne (apres un saut de ligne)</p>\n\n<!-- Ceci est un commentaire : il n\'apparait pas -->', quiz: { questions: [{ q: 'Quelle balise donne le titre le plus important ?', options: ['<h6>', '<h1>', '<h3>', '<title>'], answer: 1 }, { q: 'Quelle balise fait un saut de ligne sans balise fermante ?', options: ['<p>', '<br>', '<hr>', '<div>'], answer: 1 }] } },
        { id: 3, title: 'Les Listes, Images et Liens : Enrichir ta Page', content: 'Maintenant que tu sais ecrire du texte, voyons comment ajouter des listes, des images et des liens !\n\nLes listes :\n- <ul> : "unordered list" = liste non-ordonnee. Les elements sont precedes d\'une puce (un point).\n- <ol> : "ordered list" = liste ordonnee. Les elements sont numerotes (1, 2, 3...).\n- <li> : "list item" = chaque element de la liste, que ce soit dans <ul> ou <ol>.\n\nLes images :\n- <img> : affiche une image. C\'est une balise "orpheline" (pas de fermeture).\n   - src="fichier.jpg" : l\'attribut qui indique OU est l\'image.\n   - alt="description" : l\'attribut qui decrit l\'image si elle ne charge pas (et pour les aveugles).\n   - width="200" : la largeur en pixels.\n\nLes liens :\n- <a> : "anchor" = ancre, cree un lien cliquable.\n   - href="https://site.com" : l\'attribut qui indique la DESTINATION du lien.\n   - target="_blank" : attribut optionnel qui ouvre le lien dans un nouvel onglet.\n   - Le texte entre <a> et </a> est ce que l\'utilisateur voit et clique.', code: '<h2>Liste de courses (avec des puces)</h2>\n<ul>\n    <li>Pain</li>\n    <li>Lait</li>\n    <li>Oeufs</li>\n</ul>\n\n<h2>Top 3 des langages (numerote)</h2>\n<ol>\n    <li>Python</li>\n    <li>JavaScript</li>\n    <li>HTML</li>\n</ol>\n\n<img src="logo-codelux.png" alt="Logo de CodeLux Academy" width="200">\n\n<p>Visite notre site :\n<a href="https://codelux.com" target="_blank">\n    Clique ici pour voir CodeLux\n</a>\n</p>', quiz: { questions: [{ q: 'Quelle balise cree une liste avec des puces ?', options: ['<ol>', '<ul>', '<list>', '<li>'], answer: 1 }, { q: 'Quel attribut de <a> indique la destination du lien ?', options: ['src', 'href', 'link', 'url'], answer: 1 }] } },
        { id: 4, title: 'Les Tableaux et Formulaires : Organiser et Collecter', content: 'Les tableaux permettent d\'afficher des donnees en lignes et colonnes. Les formulaires permettent aux utilisateurs d\'envoyer des informations.\n\nLes tableaux :\n- <table> : cree le tableau.\n- <tr> : "table row" = une ligne du tableau.\n- <th> : "table header" = une cellule d\'entete (le texte est en gras).\n- <td> : "table data" = une cellule normale.\n\nLes formulaires :\n- <form> : cree un formulaire. action="..." est l\'URL ou les donnees sont envoyees. method="POST" cache les donnees, "GET" les met dans l\'URL.\n- <label> : un texte descriptif pour un champ. L\'attribut for="..." le lie a un input.\n- <input> : un champ de saisie. Le type change son apparence :\n   - type="text" : un champ pour ecrire du texte.\n   - type="email" : un champ pour un email (verifie le format).\n   - type="password" : cache ce qu\'on tape.\n   - type="number" : seulement des chiffres.\n   - required : rend le champ obligatoire.\n- <textarea> : un grand champ pour ecrire un message.\n- <select> et <option> : une liste deroulante.\n- <button> : un bouton cliquable. type="submit" envoie le formulaire.', code: '<h2>Tableau des utilisateurs</h2>\n<table border="1">\n    <tr>\n        <th>Nom</th>\n        <th>Age</th>\n        <th>Ville</th>\n    </tr>\n    <tr>\n        <td>Alice</td>\n        <td>25</td>\n        <td>Paris</td>\n    </tr>\n    <tr>\n        <td>Bob</td>\n        <td>30</td>\n        <td>Lyon</td>\n    </tr>\n</table>\n\n<h2>Formulaire d\'inscription</h2>\n<form action="/inscription" method="POST">\n    <label for="nom">Nom :</label>\n    <input type="text" id="nom" name="nom" required>\n    <br>\n    \n    <label for="email">Email :</label>\n    <input type="email" id="email" name="email">\n    <br>\n    \n    <label for="pays">Pays :</label>\n    <select id="pays" name="pays">\n        <option value="fr">France</option>\n        <option value="ci">Cote d\'Ivoire</option>\n    </select>\n    <br>\n    \n    <button type="submit">S\'inscrire</button>\n</form>', quiz: { questions: [{ q: 'Quelle balise cree une cellule d\'entete dans un tableau ?', options: ['<td>', '<th>', '<tr>', '<thead>'], answer: 1 }, { q: 'Quel attribut rend un champ obligatoire ?', options: ['obligatoire', 'required', 'force', 'must'], answer: 1 }] } },
        { id: 5, title: 'Les Balises Semantiques : Header, Nav, Main, Footer', content: 'Les balises semantiques donnent du SENS a ta page. Au lieu d\'utiliser des <div> (qui ne veulent rien dire), on utilise des balises qui expliquent CE QUE contient chaque partie. Cela aide les navigateurs, les moteurs de recherche (Google) et les personnes handicapées (lecteurs d\'ecran) a comprendre ta page.\n\nVoici les principales balises semantiques :\n- <header> : l\'en-tete de la page ou d\'une section. Contient generalement le logo, le titre du site, et parfois la barre de navigation.\n- <nav> : la section de navigation. Contient les liens vers les differentes pages du site (menu).\n- <main> : le contenu PRINCIPAL de la page. Il ne doit y avoir qu\'UN SEUL <main> par page.\n- <section> : une section thematique. Regroupe du contenu qui parle du meme sujet (ex: section "Cours", section "A propos").\n- <article> : un contenu independant et autonome (ex: un article de blog, une actualite). Il pourrait etre repris tout seul.\n- <aside> : un contenu en complement (ex: une barre laterale, des publicites).\n- <footer> : le pied de page. Contient generalement le copyright, les mentions legales, les liens de contact.\n- <div> : une balise generique sans sens particulier (a utiliser quand aucune balise semantique ne convient).', code: '<!DOCTYPE html>\n<html>\n<head>\n    <title>Mon Site - Accueil</title>\n</head>\n<body>\n    <!-- En-tete du site -->\n    <header>\n        <h1>CodeLux Academy</h1>\n        <!-- Barre de navigation -->\n        <nav>\n            <a href="/">Accueil</a>\n            <a href="/cours">Cours</a>\n            <a href="/a-propos">A propos</a>\n            <a href="/contact">Contact</a>\n        </nav>\n    </header>\n\n    <!-- Contenu principal -->\n    <main>\n        <section>\n            <h2>Bienvenue sur CodeLux</h2>\n            <p>Apprends a coder gratuitement !</p>\n        </section>\n        \n        <article>\n            <h3>Nouveau cours : Python</h3>\n            <p>Decouvre le langage Python en 7 lecons.</p>\n        </article>\n    </main>\n\n    <!-- Pied de page -->\n    <footer>\n        <p>&copy; 2026 CodeLux Academy</p>\n        <p>Contact : contact@codelux.com</p>\n    </footer>\n</body>\n</html>', quiz: { questions: [{ q: 'Quelle balise semantique represente le pied de page ?', options: ['<header>', '<footer>', '<bottom>', '<pied>'], answer: 1 }, { q: 'Quelle balise contient les liens de navigation du site ?', options: ['<menu>', '<nav>', '<ul>', '<links>'], answer: 1 }] } }
    ],
    exam: { passingScore: 6,
        questions: [
            { q: 'Que contient <head> ?', options: ['Le contenu visible', 'Infos pour le navigateur', 'Les images', 'Les videos'], answer: 1 },
            { q: 'Balise pour le plus grand titre ?', options: ['<h6>', '<h1>', '<h3>', '<title>'], answer: 1 },
            { q: 'Balise pour saut de ligne ?', options: ['<p>', '<br>', '<hr>', '<div>'], answer: 1 },
            { q: 'Balise pour liste a puces ?', options: ['<ol>', '<ul>', '<list>', '<li>'], answer: 1 },
            { q: 'Attribut de <a> pour la destination ?', options: ['src', 'href', 'link', 'url'], answer: 1 },
            { q: 'Balise pour entete de tableau ?', options: ['<td>', '<th>', '<tr>', '<thead>'], answer: 1 },
            { q: 'Attribut pour champ obligatoire ?', options: ['obligatoire', 'required', 'force', 'must'], answer: 1 },
            { q: 'Balise semantique pour pied de page ?', options: ['<header>', '<footer>', '<bottom>', '<pied>'], answer: 1 },
            { q: 'Balise semantique pour navigation ?', options: ['<menu>', '<nav>', '<ul>', '<links>'], answer: 1 },
            { q: 'Balise pour un paragraphe ?', options: ['<p>', '<par>', '<text>', '<pg>'], answer: 0 }
        ]
    }
};

COURSES.css = {
    title: 'CSS', icon: 'fa-brands fa-css3-alt',
    lessons: [
        { id: 1, title: 'C\'est quoi CSS ? Les Selecteurs', content: 'CSS (Cascading Style Sheets) donne du style a tes pages HTML. Si HTML est le squelette d\'une maison, CSS est la peinture, les meubles, la decoration. Tu peux changer les couleurs, les polices, les tailles. Les selecteurs permettent de cibler les elements : par nom de balise (p, h1), par classe (.maClasse), par id (#monId). Les classes commencent par un point et les ids par un diese #. On peut utiliser plusieurs classes sur un meme element.', code: '/* Selecteur par balise */\nbody {\n    background-color: #0f0f1a;\n    color: white;\n    font-family: Arial;\n}\n\nh1 {\n    color: #6c5ce7;\n    text-align: center;\n}\n\n/* Selecteur par classe */\n.carte {\n    background: rgba(108, 92, 231, 0.1);\n    padding: 20px;\n    border-radius: 12px;\n}\n\n/* Selecteur par id */\n#special {\n    border: 2px solid gold;\n}', quiz: { questions: [{ q: 'Que signifie CSS ?', options: ['Cascading Style Sheets', 'Computer Style Sheets', 'Color Style System', 'Creative Style Sheets'], answer: 0 }, { q: 'Comment cible-t-on une classe en CSS ?', options: ['#nom', '.nom', 'nom', '[nom]'], answer: 1 }] } },
        { id: 2, title: 'Les Couleurs, Polices et Tailles', content: 'Avec CSS, tu peux changer la couleur du texte (color) et la couleur de fond (background-color). Les couleurs peuvent s\'ecrire en anglais (red, blue), en hexadecimal (#ff0000 pour rouge), ou en RGB (rgb(255,0,0)). Tu peux aussi changer la police (font-family), la taille (font-size en pixels px), le poids (font-weight: bold) et l\'alignement (text-align: center).', code: 'h1 {\n    color: #6c5ce7;\n    font-family: "Segoe UI", Arial, sans-serif;\n    font-size: 32px;\n    font-weight: bold;\n    text-align: center;\n}\n\np {\n    color: #cccccc;\n    font-size: 16px;\n    line-height: 1.5;\n}\n\n.special {\n    background-color: #6c5ce7;\n    color: white;\n    padding: 10px;\n    border-radius: 8px;\n}\n\n.rouge { color: #ff0000; }\n.vert { color: #00ff00; }\n.bleu { color: #0000ff; }', quiz: { questions: [{ q: 'Propriete pour la couleur du texte ?', options: ['couleur', 'color', 'text-color', 'font-color'], answer: 1 }, { q: 'Hexadecimal pour rouge ?', options: ['#00ff00', '#ff0000', '#0000ff', '#ffffff'], answer: 1 }] } },
        { id: 3, title: 'Le Box Model : Margin, Padding, Border', content: 'En CSS, chaque element est une boite. Le padding est l\'espace a l\'interieur de la boite (entre le contenu et le bord). Le margin est l\'espace a l\'exterieur de la boite (entre les elements). Le border est le tour de la boite. C\'est comme emballer un cadeau : le padding est le papier a l\'interieur, le border est le ruban, et le margin est l\'espace entre les cadeaux. On peut regler chaque cote separement : padding-top, padding-right, padding-bottom, padding-left.', code: '.boite {\n    /* Espace interieur */\n    padding: 20px;\n    padding-top: 10px;\n    padding-left: 15px;\n    \n    /* Bordure */\n    border: 2px solid #6c5ce7;\n    border-radius: 12px;\n    \n    /* Espace exterieur */\n    margin: 15px;\n    margin-bottom: 30px;\n    \n    background-color: rgba(108, 92, 231, 0.1);\n}\n\n/* Exemple : centrer une boite */\n.centre {\n    width: 300px;\n    margin: 0 auto;  /* Centre horizontalement */\n}', quiz: { questions: [{ q: 'Que fait padding ?', options: ['Espace interieur', 'Espace exterieur', 'La bordure', 'La couleur'], answer: 0 }, { q: 'Que fait margin ?', options: ['Espace interieur', 'Espace exterieur', 'La bordure', 'La couleur'], answer: 1 }] } },
        { id: 4, title: 'Flexbox et Grid : Mise en Page', content: 'Flexbox est ideal pour aligner des elements sur une ligne ou une colonne. Avec display: flex, les elements se mettent cote a cote. justify-content aligne horizontalement (center, space-between, space-around). align-items aligne verticalement (center, flex-start, flex-end). flex-wrap: wrap permet aux elements de passer a la ligne. CSS Grid est pour des mises en page 2D (lignes ET colonnes). Avec grid-template-columns, tu definis le nombre et la taille des colonnes.', code: '/* Flexbox */\n.conteneur {\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n    flex-wrap: wrap;\n    gap: 20px;\n}\n\n.carte {\n    flex: 1;\n    min-width: 200px;\n    padding: 20px;\n    background: rgba(108, 92, 231, 0.1);\n    border-radius: 12px;\n    text-align: center;\n}\n\n/* Grid */\n.grille {\n    display: grid;\n    grid-template-columns: repeat(3, 1fr);\n    gap: 15px;\n}\n\n.entete {\n    grid-column: 1 / -1;  /* Prend toute la largeur */\n}', quiz: { questions: [{ q: 'Propriete pour activer Flexbox ?', options: ['display: block', 'display: flex', 'display: grid', 'display: inline'], answer: 1 }, { q: 'justify-content: center centre quoi ?', options: ['Horizontalement', 'Verticalement', 'Les deux', 'Rien'], answer: 0 }] } },
        { id: 5, title: 'Animations et Transitions', content: 'Les transitions (transition) animent les changements d\'etat. Quand tu survoles un element, la transition s\'active en douceur. Les animations (@keyframes) peuvent se repeter en boucle et etre plus complexes. C\'est comme un dessin anime : tu definis le debut (from ou 0%) et la fin (to ou 100%), et CSS calcule les etapes intermediaires ! transform permet de deplacer (translate), tourner (rotate), agrandir (scale) un element.', code: '.bouton {\n    background: #6c5ce7;\n    color: white;\n    padding: 15px 30px;\n    border-radius: 8px;\n    border: none;\n    cursor: pointer;\n    transition: all 0.3s ease;\n}\n\n.bouton:hover {\n    transform: scale(1.1);\n    background: #a29bfe;\n    box-shadow: 0 10px 30px rgba(108,92,231,0.4);\n}\n\n@keyframes fondu {\n    from { opacity: 0; transform: translateY(20px); }\n    to { opacity: 1; transform: translateY(0); }\n}\n\n.nouveau {\n    animation: fondu 0.5s ease;\n}\n\n@keyframes tourner {\n    0% { transform: rotate(0deg); }\n    100% { transform: rotate(360deg); }\n}\n\n.loading {\n    animation: tourner 2s linear infinite;\n}', quiz: { questions: [{ q: 'Propriete pour animer les changements d\'etat ?', options: ['animation', 'transition', 'transform', 'move'], answer: 1 }, { q: 'Mot-cle pour creer une animation personnalisee ?', options: ['@animation', '@keyframes', '@motion', '@frames'], answer: 1 }] } }
    ],
    exam: { passingScore: 6,
        questions: [
            { q: 'Que signifie CSS ?', options: ['Cascading Style Sheets', 'Computer Style Sheets', 'Color Style System', 'Creative Style Sheets'], answer: 0 },
            { q: 'Propriete pour couleur du texte ?', options: ['couleur', 'color', 'text-color', 'font-color'], answer: 1 },
            { q: 'Hexadecimal pour rouge ?', options: ['#00ff00', '#ff0000', '#0000ff', '#ffffff'], answer: 1 },
            { q: 'Que fait padding ?', options: ['Espace interieur', 'Espace exterieur', 'Bordure', 'Ombre'], answer: 0 },
            { q: 'Que fait margin ?', options: ['Espace interieur', 'Espace exterieur', 'Bordure', 'Ombre'], answer: 1 },
            { q: 'Propriete pour Flexbox ?', options: ['display: block', 'display: flex', 'display: grid', 'display: inline'], answer: 1 },
            { q: 'justify-content centre quoi ?', options: ['Horizontalement', 'Verticalement', 'Les deux', 'Rien'], answer: 0 },
            { q: 'Propriete pour transition ?', options: ['transition', 'animation', 'transform', 'move'], answer: 0 },
            { q: 'Mot-cle pour animation perso ?', options: ['@animation', '@keyframes', '@motion', '@frames'], answer: 1 },
            { q: 'Que fait border-radius ?', options: ['Arrondit les coins', 'Ajoute bordure', 'Change couleur', 'Ajoute ombre'], answer: 0 }
        ]
    }
};

COURSES.sql = {
    title: 'SQL', icon: 'fa-solid fa-database',
    lessons: [
        { id: 1, title: 'C\'est quoi SQL ?', content: 'SQL (Structured Query Language) est le langage pour parler aux bases de donnees. Une base de donnees, c\'est comme un grand classeur qui range des informations : noms, ages, emails, etc. Avec SQL, tu peux ajouter, chercher, modifier ou supprimer des informations. Les donnees sont rangees dans des "tables" comme des feuilles Excel. Chaque colonne est un type d\'info (nom, age) et chaque ligne est une personne.', code: '-- Commentaire en SQL\n\n-- SELECT : chercher des informations\n-- * veut dire toutes les colonnes\nSELECT * FROM utilisateurs;\n\n-- Selectionner seulement certaines colonnes\nSELECT prenom, age FROM utilisateurs;\n\n-- Avec un filtre\nSELECT * FROM utilisateurs WHERE age >= 18;\n\n-- Compter le nombre de lignes\nSELECT COUNT(*) FROM utilisateurs;', quiz: { questions: [{ q: 'Que signifie SQL ?', options: ['Simple Query Language', 'Structured Query Language', 'Standard Question Language', 'System Query Language'], answer: 1 }, { q: 'Quelle commande lit les donnees ?', options: ['SELECT', 'INSERT', 'UPDATE', 'DELETE'], answer: 0 }] } },
        { id: 2, title: 'Filtrer avec WHERE', content: 'La clause WHERE permet de filtrer les resultats. Tu peux chercher des personnes qui ont un certain age, un certain nom, ou qui habitent dans une ville precise. Les operateurs sont : = (egal), < (plus petit), > (plus grand), >=, <=, != (different), LIKE (contient un mot), IN (dans une liste), BETWEEN (entre deux valeurs). Tu peux combiner avec AND (ET) et OR (OU).', code: '-- Exact\nSELECT * FROM utilisateurs WHERE prenom = "Alice";\n\n-- Comparaison\nSELECT * FROM utilisateurs WHERE age >= 18;\n\n-- Plusieurs conditions\nSELECT * FROM utilisateurs\nWHERE age >= 18 AND ville = "Paris";\n\n-- Chercher un mot\nSELECT * FROM utilisateurs\nWHERE prenom LIKE "%oth%";\n\n-- Entre deux valeurs\nSELECT * FROM utilisateurs\nWHERE age BETWEEN 20 AND 30;\n\n-- Dans une liste\nSELECT * FROM utilisateurs\nWHERE ville IN ("Paris", "Lyon");', quiz: { questions: [{ q: 'Quelle clause filtre les resultats ?', options: ['ORDER BY', 'WHERE', 'GROUP BY', 'HAVING'], answer: 1 }, { q: 'Quel operateur cherche un mot dans un texte ?', options: ['=', 'LIKE', 'IN', 'BETWEEN'], answer: 1 }] } },
        { id: 3, title: 'Trier, Grouper et Limiter', content: 'Tu peux trier les resultats avec ORDER BY (par ordre alphabetique ou numerique). ASC pour du plus petit au plus grand (A a Z), DESC pour l\'inverse (Z a A). LIMIT permet de prendre seulement les premiers resultats. GROUP BY regroupe les donnees identiques et s\'utilise avec des fonctions comme COUNT, SUM, AVG, MIN, MAX. HAVING est comme WHERE mais pour les groupes.', code: '-- Trier\nSELECT * FROM utilisateurs\nORDER BY age ASC;  -- Du plus jeune\n\nSELECT * FROM utilisateurs\nORDER BY age DESC; -- Du plus vieux\n\n-- Limiter\nSELECT * FROM utilisateurs\nORDER BY age DESC\nLIMIT 5;\n\n-- Grouper et compter\nSELECT ville, COUNT(*) AS nombre\nFROM utilisateurs\nGROUP BY ville\nORDER BY nombre DESC;\n\n-- Moyenne d\'age par ville\nSELECT ville, AVG(age) AS age_moyen\nFROM utilisateurs\nGROUP BY ville\nHAVING age_moyen > 25;', quiz: { questions: [{ q: 'Que fait ORDER BY age DESC ?', options: ['Trie du plus petit au plus grand', 'Trie du plus grand au plus petit', 'Trie alphabetique', 'Ne fait rien'], answer: 1 }, { q: 'Quelle fonction compte les lignes ?', options: ['SUM()', 'COUNT()', 'AVG()', 'MAX()'], answer: 1 }] } },
        { id: 4, title: 'Ajouter, Modifier et Supprimer', content: 'INSERT ajoute de nouvelles lignes dans la table. Il faut dire dans quelles colonnes tu veux mettre des valeurs et quelles sont ces valeurs. UPDATE modifie des lignes existantes. ATTENTION : sans WHERE, UPDATE modifie TOUTES les lignes ! DELETE supprime des lignes. Pareil, sans WHERE ca supprime tout. C\'est pour ca qu\'on fait toujours tres attention avec UPDATE et DELETE.', code: '-- Ajouter une nouvelle personne\nINSERT INTO utilisateurs (prenom, age, ville)\nVALUES ("Othniel", 22, "Paris");\n\n-- Ajouter plusieurs personnes\nINSERT INTO utilisateurs (prenom, age, ville)\nVALUES \n    ("Alice", 25, "Lyon"),\n    ("Bob", 30, "Marseille");\n\n-- Modifier l\'age de Othniel\nUPDATE utilisateurs\nSET age = 23\nWHERE prenom = "Othniel";\n\n-- Supprimer\nDELETE FROM utilisateurs\nWHERE prenom = "Othniel";\n\n-- DANGER ! Sans WHERE :\n-- DELETE FROM utilisateurs;  // Efface TOUT !', quiz: { questions: [{ q: 'Quelle commande ajoute des donnees ?', options: ['SELECT', 'INSERT', 'UPDATE', 'DELETE'], answer: 1 }, { q: 'Pourquoi faut-il WHERE avec DELETE ?', options: ['Pour etre plus rapide', 'Pour ne pas tout effacer', 'Pour trier', 'Pour compter'], answer: 1 }] } },
        { id: 5, title: 'Les Jointures (JOIN) et Relations', content: 'Les jointures permettent de melanger les informations de plusieurs tables. Par exemple, tu as une table "utilisateurs" et une table "commandes". Avec JOIN, tu peux voir quel utilisateur a fait quelle commande. INNER JOIN prend seulement ce qui correspond dans les deux tables. LEFT JOIN garde tous les elements de la table de gauche, meme s\'ils n\'ont pas de correspondance. ON indique comment les tables sont reliees (generalement par un id).', code: '-- INNER JOIN : seulement les correspondances\nSELECT u.prenom, c.produit, c.prix\nFROM utilisateurs u\nINNER JOIN commandes c\nON u.id = c.utilisateur_id;\n\n-- LEFT JOIN : garde tous les utilisateurs\nSELECT u.prenom, c.produit\nFROM utilisateurs u\nLEFT JOIN commandes c\nON u.id = c.utilisateur_id;\n\n-- Avec alias de table\nSELECT \n    u.prenom AS "Prenom",\n    COUNT(c.id) AS "Nb commandes"\nFROM utilisateurs u\nLEFT JOIN commandes c ON u.id = c.utilisateur_id\nGROUP BY u.id;', quiz: { questions: [{ q: 'Quel JOIN prend seulement les correspondances ?', options: ['LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'FULL JOIN'], answer: 2 }, { q: 'Que fait LEFT JOIN ?', options: ['Garde tous les elements de la table de gauche', 'Garde tous les elements de la table de droite', 'Garde seulement les correspondances', 'Supprime les doublons'], answer: 0 }] } }
    ],
    exam: { passingScore: 6,
        questions: [
            { q: 'Que signifie SQL ?', options: ['Simple Query', 'Structured Query', 'Standard Question', 'System Query'], answer: 1 },
            { q: 'Commande pour lire les donnees ?', options: ['SELECT', 'INSERT', 'UPDATE', 'DELETE'], answer: 0 },
            { q: 'Clause qui filtre ?', options: ['ORDER BY', 'WHERE', 'GROUP BY', 'LIMIT'], answer: 1 },
            { q: 'Operateur pour chercher un mot ?', options: ['=', 'LIKE', 'IN', 'BETWEEN'], answer: 1 },
            { q: 'ORDER BY DESC fait quoi ?', options: ['Croissant', 'Decroissant', 'Alphabetique', 'Aleatoire'], answer: 1 },
            { q: 'Commande pour ajouter ?', options: ['SELECT', 'INSERT', 'UPDATE', 'DELETE'], answer: 1 },
            { q: 'Fonction qui compte les lignes ?', options: ['SUM()', 'COUNT()', 'AVG()', 'MAX()'], answer: 1 },
            { q: 'INNER JOIN fait quoi ?', options: ['Melange correspondances', 'Supprime tables', 'Cree tables', 'Trie'], answer: 0 },
            { q: 'Que fait UPDATE ?', options: ['Ajoute', 'Modifie', 'Supprime', 'Lit'], answer: 1 },
            { q: 'Que fait DELETE ?', options: ['Ajoute', 'Modifie', 'Supprime', 'Lit'], answer: 2 }
        ]
    }
};

const EXTRA_LANGUAGES = [
    {
        id: 'java', title: 'Java', icon: 'fa-solid fa-mug-saucer', color: '#ED8B00', lessons: 5, isCompiled: true,
        lessonsData: [
            { id: 1, title: 'Decouvre Java', content: 'Java est un langage de programmation cree par Sun Microsystems (maintenant Oracle). Il est utilise partout : applications Android, logiciels d\'entreprise, sites web, et meme dans les cartes bancaires ! Java est "compile" : tu ecris ton code dans un fichier .java, tu le compiles en .class, et la JVM (Java Virtual Machine) l\'execute. L\'avantage, c\'est que ton programme peut tourner sur n\'importe quel ordinateur (Windows, Mac, Linux) sans rien changer !', code: 'public class Main {\n    public static void main(String[] args) {\n        // Affiche un message\n        System.out.println("Bonjour le monde !");\n        System.out.println("Je code en Java !");\n    }\n}', quiz: { questions: [{ q: 'Que signifie JVM ?', options: ['Java Virtual Machine', 'Java Visual Mode', 'Java Variable Memory', 'Java Version Manager'], answer: 0 }, { q: 'Quelle methode est le point d\'entree en Java ?', options: ['start()', 'main()', 'run()', 'init()'], answer: 1 }] } },
            { id: 2, title: 'Variables et Types en Java', content: 'En Java, on doit dire quel type de valeur on range dans chaque variable. C\'est ce qu\'on appelle un langage "statiquement type". Les types principaux sont : int (nombre entier), double (nombre decimal), boolean (vrai/faux), String (texte) et char (un seul caractere). On declare d\'abord le type, puis le nom, puis on peut lui donner une valeur.', code: 'int age = 25;\ndouble prix = 19.99;\nboolean estVrai = true;\nchar lettre = \'A\';\nString nom = "Othniel";\n\nSystem.out.println("Nom: " + nom);\nSystem.out.println("Age: " + age);\n\n// Calcul\nint anneeProchaine = age + 1;\nSystem.out.println("L\'an prochain: " + anneeProchaine);', quiz: { questions: [{ q: 'Quel type pour un nombre entier en Java ?', options: ['float', 'int', 'double', 'integer'], answer: 1 }, { q: 'Comment ecrit-on un texte en Java ?', options: ['String avec guillemets', 'string avec guillemets', 'str avec apostrophes', 'texte avec guillemets'], answer: 0 }] } },
            { id: 3, title: 'Conditions et Boucles en Java', content: 'Java utilise la meme syntaxe que C et C++ pour les conditions et les boucles. if/else avec parentheses pour la condition et accolades pour le bloc. La boucle for classique a trois parties : initialisation ; condition ; incrementation. La boucle while s\'execute tant que la condition est vraie.', code: 'int age = 20;\n\nif (age >= 18) {\n    System.out.println("Majeur");\n} else {\n    System.out.println("Mineur");\n}\n\n// Boucle for\nfor (int i = 0; i < 5; i++) {\n    System.out.println("Tour " + i);\n}\n\n// Boucle while\nint compteur = 0;\nwhile (compteur < 3) {\n    System.out.println("Compteur: " + compteur);\n    compteur++;\n}', quiz: { questions: [{ q: 'Operateur pour le ET logique en Java ?', options: ['and', '&&', '&', 'et'], answer: 1 }, { q: 'Que fait i++ ?', options: ['Ajoute 2', 'Ajoute 1', 'Enleve 1', 'Multiplie'], answer: 1 }] } },
            { id: 4, title: 'Les Tableaux en Java', content: 'Les tableaux en Java ont une taille fixe qu\'on definit au moment de la creation. On utilise les crochets [] pour declarer un tableau et pour acceder aux elements. La position commence a 0. La propriete length donne la taille du tableau. Si tu essayes d\'acceder a une position qui n\'existe pas, Java te donne une erreur (ArrayIndexOutOfBoundsException).', code: 'int[] nombres = new int[5];  // Tableau de 5 entiers\nnombres[0] = 10;\nnombres[1] = 20;\nnombres[2] = 30;\n\n// Declaration avec des valeurs\nString[] prenoms = {"Alice", "Bob", "Charlie"};\n\nSystem.out.println(prenoms[0]);  // Alice\nSystem.out.println("Taille: " + prenoms.length);  // 3\n\n// Parcourir\nfor (int i = 0; i < prenoms.length; i++) {\n    System.out.println(prenoms[i]);\n}\n\n// Boucle foreach\nfor (String p : prenoms) {\n    System.out.println("Bonjour " + p);\n}', quiz: { questions: [{ q: 'Quelle est la premiere position d\'un tableau ?', options: ['1', '0', '-1', 'Premier'], answer: 1 }, { q: 'Propriete pour la taille d\'un tableau en Java ?', options: ['taille', 'length', 'size()', 'count'], answer: 1 }] } },
            { id: 5, title: 'Les Classes et Objets en Java', content: 'Java est un langage oriente objet. Une classe est comme un plan de construction. Un objet est une instance de cette classe. Les classes ont des attributs (variables) et des methodes (fonctions). On utilise "new" pour creer un objet. Les attributs peuvent etre prives (private) ou publics (public). Le constructeur (avec le meme nom que la classe) initialise l\'objet.', code: 'public class Personne {\n    private String nom;\n    private int age;\n    \n    // Constructeur\n    public Personne(String nom, int age) {\n        this.nom = nom;\n        this.age = age;\n    }\n    \n    // Methode\n    public String saluer() {\n        return "Bonjour, je suis " + nom;\n    }\n    \n    // Getter\n    public int getAge() {\n        return age;\n    }\n}\n\n// Utilisation\nPersonne p = new Personne("Alice", 25);\nSystem.out.println(p.saluer());\nSystem.out.println("Age: " + p.getAge());', quiz: { questions: [{ q: 'Mot-cle pour creer un objet en Java ?', options: ['new', 'create', 'make', 'object'], answer: 0 }, { q: 'Quel mot rend un attribut accessible seulement dans la classe ?', options: ['public', 'private', 'protected', 'static'], answer: 1 }] } }
        ],
        examQuestions: [
            { q: 'Que signifie JVM ?', options: ['Java Virtual Machine', 'Java Visual Mode', 'Java Variable Memory', 'Java Version Manager'], answer: 0 },
            { q: 'Point d\'entree en Java ?', options: ['start()', 'main()', 'run()', 'init()'], answer: 1 },
            { q: 'Type pour nombre entier ?', options: ['float', 'int', 'double', 'integer'], answer: 1 },
            { q: 'Operateur ET logique ?', options: ['and', '&&', '&', 'et'], answer: 1 },
            { q: 'Mot-cle pour creer objet ?', options: ['new', 'create', 'make', 'object'], answer: 0 },
            { q: 'Attribut prive ?', options: ['public', 'private', 'protected', 'static'], answer: 1 },
            { q: 'Premiere position tableau ?', options: ['1', '0', '-1', 'Premier'], answer: 1 },
            { q: 'Propriete taille tableau ?', options: ['taille', 'length', 'size()', 'count'], answer: 1 },
            { q: 'Que fait i++ ?', options: ['Ajoute 2', 'Ajoute 1', 'Enleve 1', 'Multiplie'], answer: 1 },
            { q: 'Constructeur en Java ?', options: ['init()', 'NomClasse()', 'construct()', 'build()'], answer: 1 }
        ]
    },
    {
        id: 'cpp', title: 'C++', icon: 'fa-solid fa-bolt', color: '#00599C', lessons: 5, isCompiled: true,
        lessonsData: [
            { id: 1, title: 'Decouvre C++', content: 'C++ est un langage tres puissant et rapide. Il est utilise pour les jeux videos, les moteurs de recherche, les systemes d\'exploitation et les applications qui ont besoin d\'etre tres performantes. C++ a ete cree par Bjarne Stroustrup en 1985. Il ajoute la programmation orientee objet au langage C. Le code C++ est compile directement en langage machine, ce qui le rend tres rapide.', code: '#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "Bonjour le monde !" << endl;\n    cout << "Je code en C++ !" << endl;\n    return 0;\n}', quiz: { questions: [{ q: 'Qui a cree C++ ?', options: ['Bjarne Stroustrup', 'Dennis Ritchie', 'James Gosling', 'Guido van Rossum'], answer: 0 }, { q: 'Quelle bibliotheque pour cout ?', options: ['<stdio.h>', '<iostream>', '<console>', '<output>'], answer: 1 }] } },
            { id: 2, title: 'Variables et Types en C++', content: 'C++ est un langage statiquement type comme Java. Les types principaux sont : int (entier), float (decimal), double (decimal plus precis), char (caractere), bool (booleen). On peut aussi utiliser "auto" pour laisser le compilateur deviner le type tout seul. C++ est tres strict sur les types : tu ne peux pas melanger un texte et un nombre sans le faire expres.', code: 'int age = 25;\ndouble prix = 19.99;\nchar lettre = \'A\';\nbool estVrai = true;\nauto x = 42;  // Devine que c\'est un int\n\ncout << "Age: " << age << endl;\ncout << "Prix: " << prix << endl;\n\n// Calcul\nint somme = age + 5;\ncout << "Somme: " << somme << endl;', quiz: { questions: [{ q: 'Type pour un booleen en C++ ?', options: ['boolean', 'bool', 'Bool', 'true/false'], answer: 1 }, { q: 'Que fait "auto" en C++ ?', options: ['Declare auto', 'Devine le type', 'Cree un objet', 'Fait une boucle'], answer: 1 }] } },
            { id: 3, title: 'Pointeurs et References', content: 'Les pointeurs sont une particularite de C et C++. Un pointeur (*) stocke l\'adresse memoire d\'une variable au lieu de sa valeur. Une reference (&) est un alias : un autre nom pour une variable existante. C\'est tres utile pour eviter de copier de grosses donnees et pour modifier directement une variable dans une fonction. Attention : les pointeurs peuvent etre dangereux si on ne fait pas attention !', code: 'int x = 10;\nint* ptr = &x;  // ptr stocke l\'adresse de x\nint& ref = x;   // ref est un alias de x\n\ncout << "Valeur de x: " << x << endl;\ncout << "Adresse de x: " << ptr << endl;\ncout << "Valeur via pointeur: " << *ptr << endl;\n\nref = 20;  // Modifie x\ncout << "x est maintenant: " << x << endl;  // Affiche 20\n\n// Exemple avec fonction\nvoid doubleValue(int& n) {\n    n = n * 2;\n}\n\ndoubleValue(x);\ncout << "x apres double: " << x << endl;  // 40', quiz: { questions: [{ q: 'Symbole pour declarer un pointeur ?', options: ['&', '*', '->', '^'], answer: 1 }, { q: 'Comment obtenir l\'adresse d\'une variable ?', options: ['*x', '&x', '@x', 'addr(x)'], answer: 1 }] } },
            { id: 4, title: 'Les Tableaux et Vecteurs', content: 'Les tableaux en C++ sont comme en Java : taille fixe et positions qui commencent a 0. Mais C++ a aussi les vecteurs (vector) de la STL (Standard Template Library) qui peuvent changer de taille automatiquement. Les vecteurs sont plus pratiques et plus surs. On utilise .push_back() pour ajouter et .size() pour la taille.', code: '#include <vector>\n\n// Tableau classique (taille fixe)\nint nombres[5] = {10, 20, 30, 40, 50};\ncout << nombres[0] << endl;  // 10\n\n// Vecteur (taille dynamique)\nvector<string> prenoms;\nprenoms.push_back("Alice");\nprenoms.push_back("Bob");\nprenoms.push_back("Charlie");\n\ncout << prenoms[0] << endl;  // Alice\ncout << "Taille: " << prenoms.size() << endl;  // 3\n\n// Parcourir\nfor (int i = 0; i < prenoms.size(); i++) {\n    cout << prenoms[i] << endl;\n}\n\n// Boucle foreach (C++11)\nfor (string p : prenoms) {\n    cout << "Bonjour " << p << endl;\n}', quiz: { questions: [{ q: 'Conteneur dynamique de la STL ?', options: ['array', 'vector', 'list', 'map'], answer: 1 }, { q: 'Methode pour ajouter a un vecteur ?', options: ['add()', 'push_back()', 'append()', 'insert()'], answer: 1 }] } },
            { id: 5, title: 'Les Classes en C++', content: 'En C++, on utilise "class" pour creer des classes. On distingue les parties public: et private: pour controler l\'acces. Le constructeur a le meme nom que la classe et n\'a pas de type de retour. Le destructeur (~NomDeClasse) est appele quand l\'objet est detruit. C++ permet l\'heritage avec ":" et le polymorphisme avec "virtual".', code: 'class Personne {\nprivate:\n    string nom;\n    int age;\npublic:\n    // Constructeur\n    Personne(string n, int a) : nom(n), age(a) {}\n    \n    // Methode\n    void saluer() {\n        cout << "Bonjour, je suis " << nom << endl;\n    }\n    \n    // Getter\n    int getAge() { return age; }\n    \n    // Destructeur\n    ~Personne() {\n        cout << nom << " est detruit" << endl;\n    }\n};\n\nPersonne p("Alice", 25);\np.saluer();', quiz: { questions: [{ q: 'Symbole pour separer public/prive en C++ ?', options: [':', '::', '->', '.'], answer: 0 }, { q: 'Destructeur en C++ ?', options: ['~NomClasse()', 'delete()', '~delete()', 'destructor()'], answer: 0 }] } }
        ],
        examQuestions: [
            { q: 'Qui a cree C++ ?', options: ['Bjarne Stroustrup', 'Dennis Ritchie', 'James Gosling', 'Guido van Rossum'], answer: 0 },
            { q: 'Bibliotheque pour cout ?', options: ['<stdio.h>', '<iostream>', '<console>', '<output>'], answer: 1 },
            { q: 'Type pour booleen ?', options: ['boolean', 'bool', 'Bool', 'true/false'], answer: 1 },
            { q: 'Que fait auto ?', options: ['Declare', 'Devine le type', 'Cree objet', 'Boucle'], answer: 1 },
            { q: 'Symbole pointeur ?', options: ['&', '*', '->', '^'], answer: 1 },
            { q: 'Conteneur dynamique ?', options: ['array', 'vector', 'list', 'map'], answer: 1 },
            { q: 'Methode pour ajouter a un vecteur ?', options: ['add()', 'push_back()', 'append()', 'insert()'], answer: 1 },
            { q: 'Destructeur ?', options: ['~Nom()', 'delete()', '~delete()', 'destructor()'], answer: 0 },
            { q: 'Obtenir adresse variable ?', options: ['*x', '&x', '@x', 'addr(x)'], answer: 1 },
            { q: 'Heritage en C++ ?', options: ['extends', ':', 'inherits', 'implements'], answer: 1 }
        ]
    },
    {
        id: 'csharp', title: 'C#', icon: 'fa-solid fa-crosshairs', color: '#239120', lessons: 5, isCompiled: true,
        lessonsData: [
            { id: 1, title: 'Decouvre C#', content: 'C# (prononce "C sharp") est un langage cree par Microsoft en 2000. Il est utilise pour creer des applications Windows, des jeux avec Unity, des applications web et mobiles. C# est moderne, oriente objet, et tres proche de Java dans sa syntaxe. Le code C# est compile en bytecode et execute par le .NET Framework ou .NET Core.', code: 'using System;\n\nclass Program {\n    static void Main() {\n        Console.WriteLine("Bonjour le monde !");\n        Console.WriteLine("Je code en C# !");\n    }\n}', quiz: { questions: [{ q: 'Qui a cree C# ?', options: ['Google', 'Microsoft', 'Apple', 'Oracle'], answer: 1 }, { q: 'Point d\'entree en C# ?', options: ['start()', 'main()', 'Main()', 'run()'], answer: 2 }] } },
            { id: 2, title: 'Variables et Types en C#', content: 'C# est statiquement type avec possibilite d\'inference avec "var". Les types principaux sont : int, double, bool, char, string. C# a aussi des types "nullable" avec ? (ex: int? peut etre null). Les proprietes avec { get; set; } sont une facon elegante de gerer l\'acces aux attributs.', code: 'int age = 25;\ndouble prix = 19.99;\nbool estVrai = true;\nstring nom = "Othniel";\nvar x = 42;  // Devine que c\'est int\n\nint? nullable = null;  // Peut etre null\n\nConsole.WriteLine("Nom: " + nom);\nConsole.WriteLine("Age: " + age);\n\n// Interpolation de chaine\nConsole.WriteLine($"Je m\'appelle {nom} et j\'ai {age} ans");', quiz: { questions: [{ q: 'Mot-cle pour inference de type en C# ?', options: ['auto', 'var', 'let', 'dynamic'], answer: 1 }, { q: 'Comment creer un type nullable ?', options: ['int?', 'int!', 'int<>', 'nullable int'], answer: 0 }] } },
            { id: 3, title: 'Conditions, Boucles et Tableaux', content: 'C# utilise la syntaxe classique C : if/else entre parentheses, for avec trois parties, while. Les tableaux se declarent avec [] et ont une taille fixe. Les listes (List<T>) sont comme les vecteurs de C++ : taille dynamique et beaucoup de methodes utiles (Add, Remove, Contains, Sort).', code: 'int age = 18;\nif (age >= 18) {\n    Console.WriteLine("Majeur");\n} else {\n    Console.WriteLine("Mineur");\n}\n\nfor (int i = 0; i < 5; i++) {\n    Console.WriteLine($"Tour {i}");\n}\n\n// Tableau\nstring[] prenoms = {"Alice", "Bob", "Charlie"};\nConsole.WriteLine(prenoms[0]);  // Alice\n\n// Liste dynamique\nList<string> liste = new List<string>();\nliste.Add("David");\nliste.Add("Eve");\nConsole.WriteLine(liste.Count);  // 2\n\nforeach (string p in prenoms) {\n    Console.WriteLine($"Bonjour {p}");\n}', quiz: { questions: [{ q: 'Collection dynamique en C# ?', options: ['List<T>', 'ArrayList', 'Vector', 'Array'], answer: 0 }, { q: 'foreach parcourt quoi ?', options: ['Chaque element', 'Chaque position', 'Chaque type', 'Chaque classe'], answer: 0 }] } },
            { id: 4, title: 'Les Classes et Proprietes', content: 'C# propose des proprietes automatiques avec { get; set; } qui creent un champ prive en coulisse. Le constructeur s\'appelle comme la classe. Les methodes peuvent etre "virtual" (redéfinissables) et "override" (redefinition). C# a aussi des "record" pour des classes qui servent juste a stocker des donnees.', code: 'class Personne {\n    // Proprietes automatiques\n    public string Nom { get; set; }\n    public int Age { get; set; }\n    \n    // Constructeur\n    public Personne(string nom, int age) {\n        Nom = nom;\n        Age = age;\n    }\n    \n    // Methode\n    public string Saluer() {\n        return $"Bonjour, je suis {Nom}";\n    }\n}\n\nPersonne p = new Personne("Alice", 25);\nConsole.WriteLine(p.Saluer());\nConsole.WriteLine($"Age: {p.Age}");', quiz: { questions: [{ q: 'Que fait { get; set; } ?', options: ['Cree propriete', 'Cree variable', 'Cree methode', 'Cree classe'], answer: 0 }, { q: 'Mot-cle pour creer un objet ?', options: ['new', 'create', 'make', 'object'], answer: 0 }] } },
            { id: 5, title: 'LINQ et Async/Await', content: 'LINQ (Language Integrated Query) permet d\'interroger des collections avec une syntaxe proche de SQL : Where (filtre), Select (transforme), OrderBy (trie). Async/ Await permet de faire des operations longues (internet, fichiers) sans bloquer le programme. Une methode async retourne Task ou Task<T>.', code: 'using System.Linq;\n\n// LINQ : filtrer et transformer\nint[] nombres = { 1, 2, 3, 4, 5, 6, 7, 8 };\nvar pairs = nombres.Where(n => n % 2 == 0);\nvar doubles = nombres.Select(n => n * 2);\n\nConsole.WriteLine("Nombres pairs:");\nforeach (var n in pairs) {\n    Console.WriteLine(n);\n}\n\n// Async/Await\nasync Task<string> LireFichierAsync() {\n    using var reader = new StreamReader(\"fichier.txt\");\n    return await reader.ReadToEndAsync();\n}\n\n// var resultat = await LireFichierAsync();', quiz: { questions: [{ q: 'Que signifie LINQ ?', options: ['Language Integrated Query', 'Link IN Query', 'List Integration', 'Logical INQ'], answer: 0 }, { q: 'Methode LINQ pour filtrer ?', options: ['Select()', 'Where()', 'Filter()', 'Find()'], answer: 1 }] } }
        ],
        examQuestions: [
            { q: 'Qui a cree C# ?', options: ['Google', 'Microsoft', 'Apple', 'Oracle'], answer: 1 },
            { q: 'Point d\'entree en C# ?', options: ['start()', 'main()', 'Main()', 'run()'], answer: 2 },
            { q: 'Mot-cle pour inference ?', options: ['auto', 'var', 'let', 'dynamic'], answer: 1 },
            { q: 'Nullable en C# ?', options: ['int?', 'int!', 'int<>', 'nullable int'], answer: 0 },
            { q: 'Collection dynamique ?', options: ['List<T>', 'ArrayList', 'Vector', 'Array'], answer: 0 },
            { q: 'Que fait { get; set; } ?', options: ['Propriete', 'Variable', 'Methode', 'Classe'], answer: 0 },
            { q: 'Que signifie LINQ ?', options: ['Language Integrated Query', 'Link IN Query', 'List Integration', 'Logical INQ'], answer: 0 },
            { q: 'Methode LINQ pour filtrer ?', options: ['Select()', 'Where()', 'Filter()', 'Find()'], answer: 1 },
            { q: 'Mot-cle pour objet ?', options: ['new', 'create', 'make', 'object'], answer: 0 },
            { q: 'Type retour async sans valeur ?', options: ['void', 'Task', 'Task<T>', 'null'], answer: 1 }
        ]
    },
    {
        id: 'php', title: 'PHP', icon: 'fa-brands fa-php', color: '#777BB4', lessons: 4, isCompiled: false,
        lessonsData: [
            { id: 1, title: 'Decouvre PHP', content: 'PHP est un langage qui s\'execute sur le serveur. Quand tu visites un site web en PHP, le serveur execute le code et envoie le resultat (du HTML) a ton navigateur. PHP est tres utilise pour creer des sites web dynamiques comme WordPress, Facebook (a l\'origine) ou Wikipedia. Le code PHP commence par <?php et se termine par ?>.', code: '<?php\necho "Bonjour le monde !";\n$nom = "Othniel";\necho "Bonjour $nom";\n?>', quiz: { questions: [{ q: 'Ou s\'execute PHP ?', options: ['Client', 'Serveur', 'Navigateur', 'Mobile'], answer: 1 }, { q: 'Symbole pour une variable PHP ?', options: ['@', '$', '#', '&'], answer: 1 }] } },
            { id: 2, title: 'Variables et Tableaux en PHP', content: 'En PHP, les variables commencent toujours par $. PHP est dynamiquement type : pas besoin de declarer le type. Les tableaux peuvent etre indexes (position 0,1,2...) ou associatifs (avec des cles nommees). La concatenation se fait avec un point (.) et non avec +.', code: '<?php\n$age = 25;\n$nom = "Alice";\n$prix = 19.99;\n\n// Tableau indexe\n$langages = ["PHP", "JS", "Python"];\necho $langages[0];  // PHP\n\n// Tableau associatif\n$personne = [\n    "nom" => "Othniel",\n    "age" => 22\n];\necho $personne["nom"];  // Othniel\n\n// Concatenation\necho "Nom: " . $nom;\necho "Age: $age";  // Interpolation\necho \'Age: $age\';  // Pas d\'interpolation !\n?>', quiz: { questions: [{ q: 'Symbole de concatenation en PHP ?', options: ['+', '.', ',', '&'], answer: 1 }, { q: 'Comment cree-t-on un tableau associatif ?', options: ['=>', ':', '->', '='], answer: 0 }] } },
            { id: 3, title: 'Les Fonctions en PHP', content: 'On declare une fonction avec "function". Les fonctions peuvent prendre des parametres et retourner une valeur avec "return". PHP a plein de fonctions integrees : strlen() pour la longueur d\'un texte, str_replace() pour remplacer, count() pour compter les elements d\'un tableau.', code: '<?php\nfunction saluer($nom) {\n    return "Bonjour $nom !";\n}\n\necho saluer("Alice");\n\n// Fonction avec valeur par defaut\nfunction addition($a, $b = 0) {\n    return $a + $b;\n}\n\necho addition(5, 3);  // 8\necho addition(5);     // 5\n\n// Fonctions integrees\n$texte = "Bonjour le monde";\necho strlen($texte);  // 17\necho str_replace("monde", "PHP", $texte);\n?>', quiz: { questions: [{ q: 'Mot-cle pour une fonction en PHP ?', options: ['function', 'def', 'fn', 'func'], answer: 0 }, { q: 'Comment donner une valeur par defaut ?', options: ['= valeur', ': valeur', '-> valeur', '?? valeur'], answer: 0 }] } },
            { id: 4, title: 'Les Formulaires et Sessions', content: 'PHP recoit les donnees des formulaires HTML via $_GET ou $_POST. $_GET pour les donnees dans l\'URL, $_POST pour les donnees cachees. Les sessions (session_start()) permettent de garder des informations entre les pages (comme etre connecte). $_SESSION est un tableau ou tu peux stocker des donnees.', code: '<?php\nsession_start();\n\n// Recuperer les donnees d\'un formulaire\nif ($_POST["submit"]) {\n    $nom = $_POST["nom"];\n    $email = $_POST["email"];\n    echo "Merci $nom !";\n}\n\n// Stocker dans la session\n$_SESSION["utilisateur"] = $nom;\n\n// Lire depuis la session\n$user = $_SESSION["utilisateur"] ?? "Invite";\necho "Bonjour $user";\n\n// Connexion a MySQL\n$pdo = new PDO("mysql:host=localhost;dbname=test", "user", "pass");\n$stmt = $pdo->prepare("SELECT * FROM users WHERE id = ?");\n$stmt->execute([$id]);\n$user = $stmt->fetch();\n?>', quiz: { questions: [{ q: 'Quelle fonction demarre une session ?', options: ['session_start()', 'start_session()', 'begin_session()', 'open_session()'], answer: 0 }, { q: 'Superglobale pour formulaire en POST ?', options: ['$_GET', '$_POST', '$_REQUEST', '$_FORM'], answer: 1 }] } }
        ],
        examQuestions: [
            { q: 'Ou s\'execute PHP ?', options: ['Client', 'Serveur', 'Navigateur', 'Mobile'], answer: 1 },
            { q: 'Symbole variable PHP ?', options: ['@', '$', '#', '&'], answer: 1 },
            { q: 'Concatenation en PHP ?', options: ['+', '.', ',', '&'], answer: 1 },
            { q: 'Mot-cle fonction ?', options: ['function', 'def', 'fn', 'func'], answer: 0 },
            { q: 'Tableau associatif utilise ?', options: ['=>', ':', '->', '='], answer: 0 },
            { q: 'Superglobale POST ?', options: ['$_GET', '$_POST', '$_REQUEST', '$_FORM'], answer: 1 },
            { q: 'Demarrer une session ?', options: ['session_start()', 'start_session()', 'begin_session()', 'open_session()'], answer: 0 },
            { q: 'Que signifie PDO ?', options: ['PHP Data Object', 'PHP Database Option', 'Personal Data Object', 'Primary Data Object'], answer: 0 },
            { q: 'Fonction pour inclure un fichier ?', options: ['import', 'include()', 'require()', 'Les deux'], answer: 3 },
            { q: 'Operateur "different de" ?', options: ['!=', '!==', '<>', 'Tous'], answer: 3 }
        ]
    }
];

EXTRA_LANGUAGES.forEach(ext => {
    COURSES[ext.id] = {
        title: ext.title,
        icon: ext.icon,
        lessons: ext.lessonsData,
        exam: {
            passingScore: ext.lessons >= 5 ? 7 : 6,
            questions: ext.examQuestions
        }
    };
});

['ruby', 'go', 'rust', 'typescript', 'swift', 'kotlin'].forEach(id => {
    const NAMES = {
        ruby: { title: 'Ruby', icon: 'fa-solid fa-gem', creator: 'Yukihiro Matsumoto', use: 'applications web (Ruby on Rails)' },
        go: { title: 'Go', icon: 'fa-solid fa-circle', creator: 'Google', use: 'applications serveur et cloud' },
        rust: { title: 'Rust', icon: 'fa-solid fa-shield-halved', creator: 'Mozilla', use: 'systemes, navigateurs, jeux' },
        typescript: { title: 'TypeScript', icon: 'fa-solid fa-file-code', creator: 'Microsoft', use: 'grands projets web' },
        swift: { title: 'Swift', icon: 'fa-solid fa-code', creator: 'Apple', use: 'applications iPhone et Mac' },
        kotlin: { title: 'Kotlin', icon: 'fa-solid fa-wind', creator: 'JetBrains', use: 'applications Android' }
    };
    const info = NAMES[id];
    COURSES[id] = {
        title: info.title, icon: info.icon,
        lessons: [
            { id: 1, title: 'Decouvre ' + info.title, content: info.title + ' est un langage de programmation cree par ' + info.creator + '. Il est utilise principalement pour ' + info.use + '. ' + info.title + ' est connu pour sa syntaxe claire et sa facilite d\'utilisation. Dans ce cours, tu vas apprendre les bases de la programmation avec ' + info.title + ' !', code: '// Premier programme en ' + info.title + '\nprint("Bonjour le monde !")\nprint("Je code en ' + info.title + ' !")', quiz: { questions: [{ q: 'Qui a cree ' + info.title + ' ?', options: [info.creator, 'Microsoft', 'Google', 'Apple'], answer: 0 }, { q: 'A quoi sert un commentaire ?', options: ['A expliquer le code', 'A effacer', 'A imprimer', 'A ralentir'], answer: 0 }] } },
            { id: 2, title: 'Variables et Types', content: 'Les variables sont des boites pour ranger des informations. On peut y mettre des nombres, du texte, ou du vrai/faux. ' + info.title + ' est un langage moderne qui rend la programmation facile et agreable.', code: 'prenom = "Othniel"\nage = 22\nest_etudiant = True\n\nprint(prenom)\nprint(age + 1)\n\nprenom = "Ange-Aurel"\nprint(prenom)', quiz: { questions: [{ q: 'A quoi sert une variable ?', options: ['A ranger une donnee', 'A effacer', 'A dessiner', 'A naviguer'], answer: 0 }, { q: 'Si age = 10, age + 5 = ?', options: ['5', '10', '15', '105'], answer: 2 }] } },
            { id: 3, title: 'Conditions et Boucles', content: 'Les conditions (if/else) permettent de prendre des decisions. Les boucles (for, while) permettent de repeter des actions. Ce sont les bases de tous les langages de programmation.', code: 'age = 18\nif age >= 18:\n    print("Majeur")\nelse:\n    print("Mineur")\n\nfor i in range(3):\n    print("Tour", i)\n\ncompteur = 0\nwhile compteur < 3:\n    print("Compteur:", compteur)\n    compteur += 1', quiz: { questions: [{ q: 'Mot-cle pour "si" ?', options: ['si', 'if', 'when', 'maybe'], answer: 1 }, { q: 'Combien de fois range(3) repete ?', options: ['2', '3', '4', '1'], answer: 1 }] } },
            { id: 4, title: 'Fonctions et Listes', content: 'Les fonctions (def) sont des recettes reutilisables. Les listes ([]) rangent plusieurs elements. Les fonctions peuvent prendre des parametres et retourner des valeurs avec return.', code: 'def saluer(nom):\n    return "Bonjour " + nom\n\nprint(saluer("Alice"))\n\namis = ["Alice", "Bob", "Charlie"]\nprint(amis[0])\namis.append("David")\nprint(len(amis))\n\nfor ami in amis:\n    print(ami)', quiz: { questions: [{ q: 'Mot-cle pour creer une fonction ?', options: ['function', 'def', 'creer', 'faire'], answer: 1 }, { q: 'Premiere position dans une liste ?', options: ['1', '0', '-1', 'Premier'], answer: 1 }] } }
        ],
        exam: { passingScore: 6,
            questions: [
                { q: 'Qui a cree ' + info.title + ' ?', options: [info.creator, 'Microsoft', 'Google', 'Apple'], answer: 0 },
                { q: 'Mot-cle pour creer une fonction ?', options: ['function', 'def', 'creer', 'faire'], answer: 1 },
                { q: 'Premiere position liste ?', options: ['1', '0', '-1', 'Premier'], answer: 1 },
                { q: 'Mot-cle pour "si" ?', options: ['si', 'if', 'when', 'maybe'], answer: 1 },
                { q: 'A quoi sert return ?', options: ['Repeter', 'Renvoyer', 'Imprimer', 'Creer'], answer: 1 },
                { q: 'Que fait append() ?', options: ['Ajoute', 'Supprime', 'Trie', 'Compte'], answer: 0 },
                { q: 'Boucle for sert a ?', options: ['Repeter', 'Effacer', 'Verifier', 'Creer'], answer: 0 },
                { q: 'Variable permet de ?', options: ['Ranger', 'Effacer', 'Dessiner', 'Naviguer'], answer: 0 },
                { q: 'Que fait while ?', options: ['Repete tant que vrai', 'Repete pour chaque', 'Verifie', 'Cree'], answer: 0 },
                { q: 'A quoi sert un commentaire ?', options: ['Expliquer', 'Effacer', 'Imprimer', 'Ralentir'], answer: 0 }
            ]
        }
    };
});

function getCourses() { return COURSES; }
function getLanguages() { return LANGUAGES; }